-- CreateEnum
CREATE TYPE "typeUser" AS ENUM ('ADMIN', 'PACIENTE', 'PROFISSIONAL');

-- CreateEnum
CREATE TYPE "genero" AS ENUM ('MASCULINO', 'FEMININO', 'NAO_BINARIO', 'OUTROS', 'PREFIRO_NAO_INFORMAR');

-- CreateEnum
CREATE TYPE "especialidadeProfissional" AS ENUM ('ACONSELHAMENTO_LUTO', 'APOIO_PSICOLOGICO_INFANTIL', 'INTERVENCAO_EM_CRISE', 'NEUROPSICOLOGIA', 'PSICANALISE', 'PSICOLOGIA_COMPORTAMENTAL', 'PSICOLOGIA_DO_ADOLESCENTE', 'PSICOLOGIA_EDUCACIONAL', 'PSICOLOGIA_ESPORTIVA', 'PSICOLOGIA_FORENSE', 'PSICOLOGIA_ORGANIZACIONAL', 'PSICOTERAPIA_COGNITIVO_COMPORTAMENTAL', 'SAUDE_MENTAL_LGBTQIA', 'TERAPIA_DE_CASAL', 'TERAPIA_DE_GRUPO', 'TERAPIA_FAMILIAR', 'TERAPIA_HOLISTICA', 'TERAPIA_OCUPACIONAL', 'TERAPIAS_DE_TRAUMA');
